#!/bin/bash

counter_file="weather_counter"  # File to store the run counter

# Check if the counter file exists
if [ ! -f "$counter_file" ]; then
    counter=1  # First run
    echo "$counter" > "$counter_file"
    eww open weatherforecast
else
    counter=$(cat "$counter_file")
    if ((counter % 2 == 0)); then
        eww close weatherforecast
    else
        eww open weatherforecast
    fi
    echo $((counter + 1)) > "$counter_file"
fi

